### ISSUE TITLE
ErrorException Undefined array key 0 

### ISSUE THREAD

**Issue by SamuelMwangiW** [miten5/larawind#11]
The laravel/framework in the composer.json throws the Exception below. 
![image](https://user-images.githubusercontent.com/1807304/109395836-879c4c80-793f-11eb-8e85-071157ec52ac.png)
Updating composer dependencies to the latest fixes the issue. Can I share a PR with an updated `composer.json` and `package-lock.json`? In the alternative, update `README` to include the above command.

Thanks for a great admin template

**Comment by miten5** [comment]
Thank you for addressing the issue.
Yes, you can share your PR.
