### ISSUE TITLE
Unresolvable dependency resolving

### ISSUE THREAD

**Issue by kyoujuaxsal** [miten5/larawind#12]
I tried Two Factor Authentication and logged in using that account and then this problem arose.

![Screenshot 2021-02-28 120803](https://user-images.githubusercontent.com/64267246/109407742-531ba580-79be-11eb-9519-74e1562bfab3.png)

sorry for bad english.

**Comment by miten5** [comment]
Thank you for reporting this important bug.

This bug is solved and ready to use.
